language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx
# Select compatible Smalltalk image(s)
smalltalk:



- Pharo32-9.0
- Pharo64-9.0
- Pharo32-8.0
- Pharo64-8.0
- Pharo32-7.0
- Pharo64-7.0



